[application]
name = "meteorite"

[bundle]
identifier = "com.vektrace.meteorite"
publisher = "Vektrace"

icon = ["assets/icon/icon-rounded.png"]

[android]
package = "com.vektrace.meteorite"

[iOS]
bundle_id = "com.vektrace.meteorite"
