name: Rust Checks

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      important: ${{ steps.filter.outputs.important }}
    steps:
      - uses: actions/checkout@v7
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            important:
              - "**/src/**"
              - "**/tests/**"
              - "**/Cargo.toml"
              - ".cargo/**"
              - "Cargo.*"
              
  run-checks:
    name: Run Checks
    needs: changes
    if: ${{ needs.changes.outputs.important == 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.9.1

      - name: Prexec (Environment Setup)
        run: |
          case "${{ matrix.os }}" in
            *'windows'*)
              echo "OPENSSL_SRC_PERL=C:/Strawberry/perl/bin/perl" | tee -a "$GITHUB_ENV"
              ;;
          esac
          cargo update

      - name: Formatting Check
        run: cargo fmt --all --check

      - name: Clippy Check
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings

      - name: Run Tests
        run: cargo test --all-features --workspace

  checks:
    - name: Checks
      runs-on: ubuntu-latest
      needs: [changes, rust-checks]
      if: always()
      steps:
        - run: |
            if [ "${{ needs.changes.result }}" = "failure" ] || [ "${{ needs.run-checks.result }}" = "failure" ]; then
              exit 1
            fi
            exit 0